services:
  - type: web
    name: telegram-quiz-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: telegram-quiz-bot
          property: url
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER_ID
        sync: false

  - type: cron
    name: leaderboard-calculator
    env: python
    schedule: "0 0 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python calculate_leaderboards.py"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: web
          name: telegram-quiz-bot
          property: DATABASE_URL
